### ISSUE TITLE
point of this repo

### ISSUE THREAD

**Issue by dpastoor** [UMCTM/language-nm#1]
Given I already have [atom-nonmem](https://github.com/dpastoor/atom-nonmem)? What is the reason for the fragmentation?

**Comment by dpastoor** [comment]
suggestion to delete this and I will transfer ownership of the existing package to CTM to ease access rights, however it has some additional improvements, including some additional documentaiton + example snippets

**Comment by vinceaperri** [comment]
Yeah, the grammars are identical.

**Comment by dpastoor** [comment]
haha yeah thats because they came from the same tmLanguage file. I think this was @wilsonmichaelc  testing out making a package, and@vjd had forgotten I had the atom-nonmem package already. I just need to check into figure out if changing ownership from dpastoor to umctm will cause any issues with atom's package manager.

**Comment by wilsonmichaelc** [comment]
@dpastoor another option is to let me make commits to the existing atom-nonmem so I can add the autocomplete and snippets that @vjd is requesting.

**Comment by dpastoor** [comment]
@wilsonmichaelc I'd definitely be down with that then if we feel the need to migrate it 'officially' we can figure it out at that point - giving you access now...
